project:
  type: website
  output-dir: _site
  resources:
    - CNAME
    - landing.css
    - assets/**

website:
  title: "CensoLab"
  site-url: https://censolab.cl
  google-analytics: "G-KQNMTM4EDX"
  search: false
  navbar:
    left:
      - text: Explorar
        href: app/
    right:
      - text: Cómo usar
        href: como-usar/
      - text: Acerca de
        href: acerca-de/
  page-footer:
    center: "CensoLab · Censo 2024"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
